name: AdminUtilities
version: '$version'

main: org.senbler.adminUtilities.AdminUtilities
api-version: '26.1.2'
load: POSTWORLD

commands:
  adminutilities:
    description: Opens the main menu.
    usage: /adminutilities
    aliases: [adminutil, au]
    permission: AdminUtilities.main_menu
    permission-message: You don't have permission to use this command!
  freeze:
    description: Freezes a player. This prevents them from moving, interacting with blocks, and chatting.
    usage: /freeze <player>
    permission: AdminUtilities.freeze
    permission-message: You don't have permission to use this command!
  unfreeze:
    description: Unfreezes a player. The player can now move and interact as normal.
    usage: /unfreeze <player>
    permission: AdminUtilities.unfreeze
    permission-message: You don't have permission to use this command!
  spawnnpc:
    description: testing
    usage: /spawnnpc
permissions:
  AdminUtilities:
    main_menu: Allows the player to open the main menu
    freeze: Allows the player to use the freeze command
    unfreeze: Allows a player to use the unfreeze command
    edit_npc: Allows a player to edit an NPC